import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/componets/common/Navbar";
import Footer from "@/container/home/Footer";
import MobileFooter from "@/componets/common/MobileFooter";
import { AppProvider } from "@/context/AppContext";
import StoreProvider from "@/providers/StoreProvider";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AppProvider>
            <div className="hidden lg:block">
              <Navbar />
            </div>
            <Toaster position="top-right" reverseOrder={false} />
            {children}
            <div className="md:hidden">
              <MobileFooter />
            </div>
            <div className="hidden md:block">
              <Footer />
            </div>
          </AppProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
